### ISSUE TITLE
Bug related to extracting the full text from a tweet

### ISSUE THREAD

**Issue by shark4ce** [InQuest/ThreatIngestor#114]
Hi,
I noticed that for the tweets that were retweeted, the text is not extracted in its entirety, respectively, not all possible artefacts are extracted. The full text can be extracted from "retweed_status" section from a retweeted tweet's data object. 
For example, take a look to a such tweet's data object:
![image](https://user-images.githubusercontent.com/46487296/200641189-82190c23-4777-4434-959b-3e7cbaaf69c9.png)

**Comment by Hifumi1337** [comment]
@shark4ce,

New version of ThreatIngestor is now available!

Release: https://github.com/InQuest/ThreatIngestor/releases/tag/v1.0.0b9
