### ISSUE TITLE
Add configuration validation option

### ISSUE THREAD

**Issue by dspruell-i01** [InQuest/ThreatIngestor#149]
To enable better automation & confidence in configuration changes prior to reloading the tool, implement a configuration validation option similar to many other software.

The use case is to support a workflow:
1. Make changes to the program configuration.
2. Run configuration validation, ensuring that the configuration can be loaded correctly.
3. Reload or restart running service.

This workflow can also support automation for configuration management, e.g. using Ansible to deploy and validate an updated configuration before restarting the service.

Scope of validation:
- YAML config is valid/no syntax issues
- Basic ThreatIngestor config is viable, no missing required options or conflicting parameters, etc.

**Comment by azazelm3dj3d** [comment]
Hi @dspruell-i01,

I believe this issue is now resolved under PR #150. Do you have any issues with closing?

**Comment by dspruell-i01** [comment]
I think we're good! Thanks.
