### ISSUE TITLE
Add Pastebin source

### ISSUE THREAD

**Issue by rshipp** [InQuest/ThreatIngestor#25]

**Comment by deadbits** [comment]
This blog has some great code and steps on creating a Pastebin monitoring pipeline. Some steps obviously wouldn't apply here but the pastebin specific code / monitoring I think is very similar to what the source might look like?
- http://www.automatingosint.com/blog/2017/04/building-a-keyword-monitoring-pipeline-with-python-pastebin-and-searx/

**Comment by rshipp** [comment]
Thanks. Leaving these here for reference too:

* https://github.com/kevthehermit/PasteHunter
* https://github.com/xme/pastemon

**Comment by deadbits** [comment]
Also this is something to consider: https://pastebin.com/api_scraping_faq
you need a pastebin pro account to use it but its $50/lifetime acct and the scraping acct gives much better data than trying to do what pastemon or pastehunter does (gets everything, keeps track of seen pastes in a db, etc.)
