### ISSUE TITLE
Add filesystem source

### ISSUE THREAD

**Issue by rshipp** [InQuest/ThreatIngestor#34]
Point it at a file/directory and it will recursively read and extract artifacts similar to iocextract CLI.

**Comment by deadbits** [comment]
Maybe consider using `watchdog` to monitor for changes to that directory automatically and extract artifacts from any newly added files:
- https://pypi.org/project/watchdog/

**Comment by rshipp** [comment]
Interesting. I'm not sure if this will work here, I need something that doesn't run continuously and just gives me a flag or something I can check to see if there have been changes (mtime maybe?). I haven't thought too far into it.

**Comment by deadbits** [comment]
I personally think continuous  monitoring (or even periodically per day/hour)  of a path could be great. 

My use case premise was something like: Analysts put APT reports in a given directory or share drive, Threat Ingestors uses watchdog (or similar) to watch path, analyst of T.I. adds that directory as a source and all newly added reports have their artifacts automatically extracted.

Potentially on the user's pipeline they could just feed the results into an alerting list for IPS, hashes, or add YARA sigs to their internal ruleset application.

**Comment by deadbits** [comment]
Ahh gotcha 👍 i misunderstood

**Comment by rshipp** [comment]
This is now possible due to #52. @needmorecowbell has a SQS worker using watchdog locally. Need to add docs on SQS workflow (#17) and figure out how we're going to publish the "SQS worker" concept/examples... maybe wait until #40 is done too so it's not tied to SQS specifically.

**Comment by rshipp** [comment]
Closed by #60. See https://threatingestor.readthedocs.io/en/latest/extras.html#fswatcher for docs.
