### ISSUE TITLE
contact?

### ISSUE THREAD

**Issue by guzzijones** [InQuest/ThreatIngestor#76]
Not sure how to contact you.  I like your work and thanks for these repos.  I am working on a product for cyber threat intelligence using ML and statistics.  Contact me at aaron.jonen@cypherint.com if you are interested.  I would like to ask you how we can go about open sourcing it under gpl2 but also maintain some level of confidence it won't get stolen from us.  Also if you are interested I am looking for devs to help us out.

**Comment by pedramamini** [comment]
AJ,

Thanks for your kind words and for reaching out. Feel free to shoot the team an e-mail via labs@inquest.net we'll get a dialogue going there. 

Kind regards

-pedram
