### ISSUE TITLE
Returning 0 artifacts 

### ISSUE THREAD

**Issue by ardapicus** [InQuest/ThreatIngestor#80]
Hi,

When I execute threatIngestor with my config.xml, it returns 0 artifacts and does not create a csv file. Can you help?

You can find my config.xml and a sample output below:

![Screen Shot 2020-01-27 at 17 27 41](https://user-images.githubusercontent.com/40626848/73182765-b0458780-412a-11ea-8a52-e2dc4a6b7450.png)

<img width="991" alt="Screen Shot 2020-01-27 at 17 27 28" src="https://user-images.githubusercontent.com/40626848/73182774-b471a500-412a-11ea-8e75-0182451a81a0.png">

**Comment by alrawi** [comment]
change your slug value from `c2-feed` to `ioc-feed`

**Comment by cmmorrow** [comment]
Closing this issue if there's no further questions.
