### ISSUE TITLE
An issue with PyMISP

### ISSUE THREAD

**Issue by ninoseki** [InQuest/ThreatIngestor#81]
The latest version of PyMISP(v2.4.120) drops following methods which ThreatIngestor uses. 
(ref. https://github.com/MISP/PyMISP/commit/24a8f90ea830d780c13cf8383442990a3e4863b3#diff-0645334504f5c27e7d42e1f0f3cb8d6aL927-L948)

- `#add_internal_link`
- `#add_internal_text`
- `#add_internal_other`

So, as a temporary solution, prohibiting using the latest PyMISP is good IMHO.
(Note: I confirmed that ThreatIngestor works with PyMISP v2.4.119)

**Comment by ninoseki** [comment]
I created two PRs to fix this issue.

- #82: Restricting using the latest PyMISP
- #83: Updating the MISP operator to work with the latest PyMISP

My preferable one is #83 but of course the choice is yours.

**Comment by ninoseki** [comment]
@cmmorrow Now you can remove PyMISP's version restriction which is introduced by #82.
https://github.com/InQuest/ThreatIngestor/blob/master/setup.py#L26
Or should I make a patch for that?

**Comment by cmmorrow** [comment]
If you submit a PR for it, I'll merge it.
