### ISSUE TITLE
cannot run Threatingestor

### ISSUE THREAD

**Issue by EaGLe3YeS** [InQuest/ThreatIngestor#84]
cannot run the application and it keeps giving error: 
threatingestor.exceptions.IngestorError: YAML error in config

I am using the same config mentioned in the user document and not sure what is the issue, could you please help.

**Comment by cmmorrow** [comment]
Hello @EaGLe3YeS, can you post the YAML file you are using?

**Comment by Hifumi1337** [comment]
Hi, @EaGLe3YeS!

I wanted to check-in before closing this issue, just in case you would like to try again in the future.

If you're still encountering any problems, please share your `config.yml` file in a new issue. Thank you!
