### ISSUE TITLE
Add a whitelist... 

### ISSUE THREAD

**Issue by mathurin68** [InQuest/ThreatIngestor#86]
This is great!

Every now and then we get a domain from twitter that isn't malicious and blows up our security tools, is there a place to add a whitelist? 

Something like this(first 20K or something) http://s3.amazonaws.com/alexa-static/top-1m.csv.zip

Thanks!

**Comment by ninoseki** [comment]
@cmmorrow  I think adding [misp-warninglists](https://github.com/MISP/misp-warninglists) compatible white listing feature would be useful.
I will make a PR if it makes sense.

**Comment by cmmorrow** [comment]
Hello @ninoseki, yes I think this makes sense and feel free to work on it if you have the time.

**Comment by cmmorrow** [comment]
Hello @mathurin68, the MISP whitelist is included in release 1.0.0b8. I'll go ahead and close this issue.
