### ISSUE TITLE
threatingestor.exceptions.PluginError: No valid plugin 'misp' in 'threatingestor.sources'

### ISSUE THREAD

**Issue by jefere1** [InQuest/ThreatIngestor#92]
Where might I be going wrong... Am trying to set threatingestor to connect and send extracted artifacts.  I keep getting this error and  I've been googling on how to sort it out without any success

  File "/usr/local/lib/python3.6/dist-packages/threatingestor/config.py", line 114, in sources
    sources.append((source[NAME], self._load_plugin(SOURCE, source['module']), kwargs))
    │       │       │      │      │    │            │       │                  └ {'name': 'mymisp', 'url': 'https://192.168.43.192/', 'key': 'cVA4um8xhUMfTl3TEogYX7C5vDGKhJsbLquVvEUS', 'ssl': False}
    │       │       │      │      │    │            │       └ {'name': 'mymisp', 'module': 'misp', 'credentials': 'misp-auth'}
    │       │       │      │      │    │            └ 'threatingestor.sources'
    │       │       │      │      │    └ <staticmethod object at 0x7f777675e588>
    │       │       │      │      └ <threatingestor.config.Config object at 0x7f777b561438>
    │       │       │      └ 'name'
    │       │       └ {'name': 'mymisp', 'module': 'misp', 'credentials': 'misp-auth'}
    │       └ <method 'append' of 'list' objects>
    └ [('threatingestor', <class 'threatingestor.sources.twitter.Plugin'>, {'name': 'threatingestor', 'api_key': '####...

  File "/usr/local/lib/python3.6/dist-packages/threatingestor/config.py", line 50, in _load_plugin
    raise PluginError("No valid plugin '{p}' in '{t}'".format(p=plugin, t=plugin_type))
          │                                                     │         └ 'threatingestor.sources'
          │                                                     └ 'misp'
          └ <class 'threatingestor.exceptions.PluginError'>

**threatingestor.exceptions.PluginError: No valid plugin 'misp' in 'threatingestor.sources'**

**Comment by cmmorrow** [comment]
Hello @jefere1, what version of threatingestor are you running and what is you OS?

**Comment by Hifumi1337** [comment]
Hi, @jefere1!

I wanted to check-in before closing this issue, just in case you would like to try again in the future.

If you're still encountering this issue, please share your `config.yml` file in a new issue. Thank you!
