### ISSUE TITLE
No data in Hug index page

### ISSUE THREAD

**Issue by thealy** [InQuest/ThreatIngestor#96]
Hello-

New install, test using config based on RSS feeds works with output to .csv file, but when I fire up hug and go to localhost:8000, I see the menus but no data in any category. What am I missing?

Nice tool - hope to add more feeds.

**Comment by cmmorrow** [comment]
Hello @thealy! Thanks for trying out ThreatIngestor. Can you send an example of the yaml file you are using?

**Comment by loveaifeng** [comment]
how can i set proxy for the threatingestor?

**Comment by Hifumi1337** [comment]
Hi, @thealy!
I wanted to check-in before closing this issue, just in case you would like to try again in the future. If so, please open a new issue with the `config.yml` file and I'd be happy to take a closer look.
